# Generated by Django 3.0.8 on 2020-08-02 11:05

from django.db import migrations, models
import reportingTool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_patient', models.CharField(max_length=25, validators=[reportingTool.models.Patient.code_patient_validate])),
            ],
        ),
        migrations.CreateModel(
            name='Post_depistage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
