# Generated by Django 3.0.8 on 2020-08-13 00:06

from django.db import migrations, models
import reportingTool.models


class Migration(migrations.Migration):

    dependencies = [
        ('reportingTool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(null=True, validators=[reportingTool.models.Patient.age_validate]),
        ),
        migrations.AddField(
            model_name='patient',
            name='beneficiant_CD4',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='conseiller',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='depister',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='resultat',
            field=models.CharField(choices=[('P', 'Positif'), ('N', 'Négatif'), ('I', 'Indéterminer'), ('C', 'Statut connu')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='resultat_recu',
            field=models.BooleanField(null=True),
        ),
    ]
