# Generated by Django 3.0.8 on 2020-08-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportingTool', '0002_auto_20200813_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='resultat',
            field=models.CharField(blank=True, choices=[('P', 'Positif'), ('N', 'Négatif'), ('I', 'Indéterminer'), ('C', 'Statut connu')], max_length=1),
        ),
    ]
