# Generated by Django 3.0.8 on 2020-09-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportingTool', '0003_auto_20200819_0015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_depistage',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_de_depistage',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='post_de_depistage',
            field=models.CharField(choices=[('Tuberculose', 'Tuberculose'), ('CPN2 et Plus + Acccouch + CPoN', 'CPN2 et Plus + Acccouch + CPoN'), ('IST', 'IST'), ('Hospitalisation', 'Hospitalisation'), ('Index testing', 'Index testing'), ('Urgence', 'Urgence'), ('Malnutrition', 'Malnutrition'), ('Autre CDIP', 'Autre CDIP')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='beneficiant_CD4',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='conseiller',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='depister',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='genre',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='resultat',
            field=models.CharField(choices=[('Positif', 'Positif'), ('Négatif', 'Négatif'), ('Indéterminer', 'Indéterminer'), ('Statut connu', 'Statut connu')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='resultat_recu',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=3, null=True),
        ),
    ]
