# Generated by Django 3.0.8 on 2020-09-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportingTool', '0004_auto_20200901_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_de_depistage',
            field=models.DateField(null=True),
        ),
    ]
