# Generated by Django 3.0.8 on 2020-09-01 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportingTool', '0005_auto_20200901_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_de_depistage',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
